/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1      */
/*  Created On : 12-bře-2025 19:14:35                   */
/*  DBMS       : PostgreSQL                             */
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Adresa" CASCADE;
DROP TABLE IF EXISTS "Hala" CASCADE;
DROP TABLE IF EXISTS "Rezervacehaly" CASCADE;
DROP TABLE IF EXISTS "Roleuzivatelu" CASCADE;
DROP TABLE IF EXISTS "Seznamprihlasenychrezervacihracu" CASCADE;
DROP TABLE IF EXISTS "Tym" CASCADE;
DROP TABLE IF EXISTS "Uzivatel" CASCADE;
DROP TABLE IF EXISTS "Komentare" CASCADE;
DROP TABLE IF EXISTS "ReservationDeletionLog" CASCADE;

/* Create Tables */

CREATE TABLE "Adresa"
(
    "C.p." integer NULL,
    "Nazevmesta" varchar(255) NULL,
    "Psc" integer NULL,
    "Ulice" varchar(255) NULL,
    "AdresaID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    CONSTRAINT "PK_Adresa" PRIMARY KEY ("AdresaID")
);

CREATE TABLE "Hala"
(
    "Konecoteviracidoby" timestamp without time zone NULL,
    "Nazev" varchar(255) NULL,
    "Pocatekoteviracidoby" timestamp without time zone NULL,
    "HalaID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    CONSTRAINT "PK_Hala" PRIMARY KEY ("HalaID")
);

CREATE TABLE "Rezervacehaly"
(
    "Datumrezervace" date NULL,
    "Konecrezervace" timestamp without time zone NULL,
    "Zacatekrezervace" timestamp without time zone NULL,
    "RezervacehalyID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    "HalaID" integer NOT NULL,
    "UzivatelID" integer NOT NULL,
    CONSTRAINT "PK_Rezervacehaly" PRIMARY KEY ("RezervacehalyID")
);

CREATE TABLE "Roleuzivatelu"
(
    "Nazevrole" varchar(255) NULL,
    "RoleuzivateluID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    CONSTRAINT "PK_Roleuzivatelu" PRIMARY KEY ("RoleuzivateluID")
);

CREATE TABLE "Seznamprihlasenychrezervacihracu"
(
    "Stavprihlaseni" boolean NOT NULL,
    "SeznamprihlasenychrezervacihracuID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    "RezervacehalyID" integer NOT NULL,
    "UzivatelID" integer NOT NULL,
    CONSTRAINT "PK_Seznamprihlasenychrezervacihracu" PRIMARY KEY ("SeznamprihlasenychrezervacihracuID")
);

CREATE TABLE "Tym"
(
    "Nazevtymu" varchar(255) NULL,
    "TymID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    CONSTRAINT "PK_Tym" PRIMARY KEY ("TymID")
);

CREATE TABLE "Uzivatel"
(
    "Email" text NOT NULL,
    "Jmeno" varchar(255) NOT NULL,
    "Prijmeni" varchar(255) NOT NULL,
    "Telefon" text NULL,
    "profile_picture_url" text NULL,
    "UzivatelID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    "AdresaID" integer NOT NULL,
    "RoleuzivateluID" integer NOT NULL,
    "TymID" integer NOT NULL,
    CONSTRAINT "PK_Uzivatel" PRIMARY KEY ("UzivatelID")
);

CREATE TABLE "Komentare"
(
    "Text" text NOT NULL,
    "KomentarID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    "RezervacehalyID" integer NOT NULL,
    "UzivatelID" integer NOT NULL,
    CONSTRAINT "PK_Komentare" PRIMARY KEY ("KomentarID")
);

CREATE TABLE "ReservationDeletionLog"
(
    "Datumrezervace" date NULL,
    "Konecrezervace" timestamp without time zone NULL,
    "Zacatekrezervace" timestamp without time zone NULL,
    "DeletedBy" integer NOT NULL,
    "LogID" integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    CONSTRAINT "PK_ReservationDeletionLog" PRIMARY KEY ("LogID")
);

/* Create Foreign Key Constraints */

ALTER TABLE "Rezervacehaly" ADD CONSTRAINT "FK_RezervaceHaly_RezervaceSeVazeNaHalu"
    FOREIGN KEY ("HalaID") REFERENCES "Hala" ("HalaID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Rezervacehaly" ADD CONSTRAINT "FK_RezervaceHaly_TrenerRezervuje"
    FOREIGN KEY ("UzivatelID") REFERENCES "Uzivatel" ("UzivatelID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Seznamprihlasenychrezervacihracu" ADD CONSTRAINT "FK_SeznamPrihlasenychRezervaciHracu_VytvariRezervace"
    FOREIGN KEY ("RezervacehalyID") REFERENCES "Rezervacehaly" ("RezervacehalyID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Seznamprihlasenychrezervacihracu" ADD CONSTRAINT "FK_SeznamPrihlasenychRezervaciHracu_HracSePrihlasuje"
    FOREIGN KEY ("UzivatelID") REFERENCES "Uzivatel" ("UzivatelID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Uzivatel" ADD CONSTRAINT "FK_Uzivatel_MuzeMitAdresu"
    FOREIGN KEY ("AdresaID") REFERENCES "Adresa" ("AdresaID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Uzivatel" ADD CONSTRAINT "FK_Uzivatel_MaRoli"
    FOREIGN KEY ("RoleuzivateluID") REFERENCES "Roleuzivatelu" ("RoleuzivateluID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Uzivatel" ADD CONSTRAINT "FK_Uzivatel_HracTrenerJeClenem"
    FOREIGN KEY ("TymID") REFERENCES "Tym" ("TymID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Komentare" ADD CONSTRAINT "FK_Komentare_RezervaceKomentare"
    FOREIGN KEY ("RezervacehalyID") REFERENCES "Rezervacehaly" ("RezervacehalyID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Komentare" ADD CONSTRAINT "FK_Komentare_UzivatelKomentuje"
    FOREIGN KEY ("UzivatelID") REFERENCES "Uzivatel" ("UzivatelID") ON DELETE NO ACTION ON UPDATE NO ACTION;